package com.capgemini.domain;
// Generated Aug 17, 2016 8:43:48 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project", catalog = "starterkit_jpa")
public class Project implements java.io.Serializable {

	private Integer id;
	private String name;
	private String type;
	private Date startOfProject;
	private Date endOfProject;
	private Set<Employee2project> employee2projects = new HashSet<Employee2project>(0);

	public Project() {
	}

	public Project(String name, String type, Date startOfProject, Date endOfProject) {
		this.name = name;
		this.type = type;
		this.startOfProject = startOfProject;
		this.endOfProject = endOfProject;
	}

	public Project(String name, String type, Date startOfProject, Date endOfProject,
			Set<Employee2project> employee2projects) {
		this.name = name;
		this.type = type;
		this.startOfProject = startOfProject;
		this.endOfProject = endOfProject;
		this.employee2projects = employee2projects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type", nullable = false, length = 9)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "startOfProject", nullable = false, length = 10)
	public Date getStartOfProject() {
		return this.startOfProject;
	}

	public void setStartOfProject(Date startOfProject) {
		this.startOfProject = startOfProject;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "endOfProject", nullable = false, length = 10)
	public Date getEndOfProject() {
		return this.endOfProject;
	}

	public void setEndOfProject(Date endOfProject) {
		this.endOfProject = endOfProject;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set<Employee2project> getEmployee2projects() {
		return this.employee2projects;
	}

	public void setEmployee2projects(Set<Employee2project> employee2projects) {
		this.employee2projects = employee2projects;
	}

}
